spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Engineer6544
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
# For default login credentials
#  .security:
#    .user:
#      .name: elbrus
#      .password: engineer